spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/itokennn/itoken-config
          search-paths: respo
          username: 493886277@qq.com
          password: sdqhyk123
  boot:
    admin:
      client:
        url: http://192.168.211.133:8084
  zipkin:
    base-url: http://192.168.211.133:9411
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.211.133:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info